description: >
  Custom translation module to translate legacy Fes-style global-variable events
  into dojo-compatible format. Planned retirement when HA allows templating of
  event type in automation.  Allows dynamic volume resolution. Injects
  'volume_entity' based on provided cabinet sensor entity ID. Routes to
  dojo-style 'set_variable', 'remove_variable', or 'clear_variables' handlers.
  Verifies write permission using the cabinet manifest stored in
  'sensor.cabinet_manifest'.
mode: parallel
triggers:
  - trigger: event
    event_type: set_variable_legacy
    id: set
  - trigger: event
    event_type: remove_variable_legacy
    id: remove
  - trigger: event
    event_type: clear_variable_legacy
    id: clear
conditions: []
actions:
  - variables:
      vol_system: sensor.variables
      vol_home: sensor.household_cabinet
      vol_family: sensor.surname_family_cabinet
      vol_kata: sensor.zen_kata_storage_cabinet
      vol_history: sensor.zen_history_cabinet
      vol_friday_history: sensor.zen_friday_history_cabinet
      vol_dojo: sensor.zen_dojo_cabinet
      vol_summary: sensor.ai_summary_cabinet
      vol_scratch: ""
      vol_friday: sensor.friday_s_cabinet
      vol_user1: sensor.user1_cabinet
      vol_user1: sensor.user2_cabinet
      vol_charming: ""
      event_type: "{{ trigger.event.event_type }}"
      key: "{{ trigger.event.data.key | default('') }}"
      value: "{{ trigger.event.data.value | default('') }}"
      set_timestamp: "{{ trigger.event.data.set_timestamp | default(false) }}"
      volume_entity: "{{ trigger.event.data.volume_entity | default('') }}"
      log_events: "{{ trigger.event.data.log_events | default(false) }}"
  - alias: Log the transaction?
    if:
      - alias: Log?
        condition: template
        value_template: "{{ log_events }}"
    then:
      - data:
          name: "{{ event_type }}:"
          message: >
            {{ key | default('-') }} {%- if event_type == 'set_variable_legacy'
            -%}           
              : {{ value | default('not defined!')}}.
            {%- endif -%}
        action: logbook.log
  - choose:
      - conditions:
          - alias: AI Summarizer Cabinet
            condition: template
            value_template: "{{ volume_entity == vol_summary }}"
        sequence:
          - choose:
              - conditions:
                  - condition: trigger
                    id:
                      - set
                sequence:
                  - alias: Set - Katas
                    event: set_variable_ai_summary_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
                      value: "{{  value | default('') }}"
                      set_timestamp: "{{ set_timestamp | default(false) }}"
                      log_events: "{{ log_events }}"
              - conditions:
                  - condition: trigger
                    id:
                      - remove
                sequence:
                  - alias: Remove - Katas
                    event: remove_variable_ai_summary_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
              - conditions:
                  - condition: trigger
                    id:
                      - clear
                sequence:
                  - alias: Clear - Katas
                    event: clear_variable_ai_summary_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
        alias: AI Summarizer Cabinet
      - conditions:
          - alias:  Household Storage
            condition: template
            value_template: "{{ volume_entity == vol_home }}"
        sequence:
          - choose:
              - conditions:
                  - condition: trigger
                    id:
                      - set
                sequence:
                  - alias: Set - Household
                    event: set_variable_household_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
                      value: "{{  value | default('') }}"
                      set_timestamp: "{{ set_timestamp | default(false) }}"
                      log_events: "{{ log_events }}"
              - conditions:
                  - condition: trigger
                    id:
                      - remove
                sequence:
                  - alias: Remove - Household
                    event: remove_variable_household_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
              - conditions:
                  - condition: trigger
                    id:
                      - clear
                sequence:
                  - alias: Clear - Household
                    event: clear_variable_household_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
      - conditions:
          - alias: Family Storage
            condition: template
            value_template: "{{ volume_entity == vol_family }}"
        sequence:
          - choose:
              - conditions:
                  - condition: trigger
                    id:
                      - set
                sequence:
                  - alias: Set - Family
                    event: set_variable_family_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
                      value: "{{  value | default('') }}"
                      set_timestamp: "{{ set_timestamp | default(false) }}"
                      log_events: "{{ log_events }}"
              - conditions:
                  - condition: trigger
                    id:
                      - remove
                sequence:
                  - alias: Remove - Family
                    event: remove_variable_family_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
              - conditions:
                  - condition: trigger
                    id:
                      - clear
                sequence:
                  - alias: Clear - Family
                    event: clear_variable_family_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
      - conditions:
          - alias: AI User - Friday Volume
            condition: template
            value_template: "{{ volume_entity == vol_friday }}"
        sequence:
          - choose:
              - conditions:
                  - condition: trigger
                    id:
                      - set
                sequence:
                  - event: set_variable_friday_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
                      value: "{{  value | default('') }}"
                      set_timestamp: "{{ set_timestamp | default(false) }}"
                      log_events: "{{ log_events }}"
                    alias: Set - Friday
              - conditions:
                  - condition: trigger
                    id:
                      - remove
                sequence:
                  - event: remove_variable_friday_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
                    alias: Remove - Friday
              - conditions:
                  - condition: trigger
                    id:
                      - clear
                sequence:
                  - event: clear_variables_friday_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
                    alias: Clear - Friday
      - conditions:
          - alias: User - Nathan Volume
            condition: template
            value_template: "{{ volume_entity == vol_user1 }}"
        sequence:
          - choose:
              - conditions:
                  - condition: trigger
                    id:
                      - set
                sequence:
                  - alias: Set - user1
                    event: set_variable_user1_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
                      value: "{{  value | default('') }}"
                      set_timestamp: "{{ set_timestamp | default(false) }}"
                      log_events: "{{ log_events }}"
              - conditions:
                  - condition: trigger
                    id:
                      - remove
                sequence:
                  - alias: Remove - user1
                    event: remove_variable_user1_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
              - conditions:
                  - condition: trigger
                    id:
                      - clear
                sequence:
                  - alias: Clear - user1
                    event: clear_variables_user1_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
      - conditions:
          - alias: user2 Volume
            condition: template
            value_template: "{{ volume_entity == vol_user2 }}"
        sequence:
          - choose:
              - conditions:
                  - condition: trigger
                    id:
                      - set
                sequence:
                  - alias: Set - user2
                    event: set_variable_user2_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
                      value: "{{  value | default('') }}"
                      set_timestamp: "{{ set_timestamp | default(false) }}"
                      log_events: "{{ log_events }}"
              - conditions:
                  - condition: trigger
                    id:
                      - remove
                sequence:
                  - alias: Remove - user2
                    event: remove_variable_user2_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
              - conditions:
                  - condition: trigger
                    id:
                      - clear
                sequence:
                  - alias: Clear - user2
                    event: clear_variable_user2_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
      - conditions:
          - alias: Zen Kata Storage
            condition: template
            value_template: "{{ volume_entity == vol_kata }}"
        sequence:
          - choose:
              - conditions:
                  - condition: trigger
                    id:
                      - set
                sequence:
                  - alias: Set - Katas
                    event: set_variable_zen_kata_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
                      value: "{{  value | default('') }}"
                      set_timestamp: "{{ set_timestamp | default(false) }}"
                      log_events: "{{ log_events }}"
              - conditions:
                  - condition: trigger
                    id:
                      - remove
                sequence:
                  - alias: Remove - Katas
                    event: remove_variable_zen_kata_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
              - conditions:
                  - condition: trigger
                    id:
                      - clear
                sequence:
                  - alias: Clear - Katas
                    event: clear_variable_zen_kata_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
      - conditions:
          - alias: Zen History Cabinet
            condition: template
            value_template: "{{ volume_entity == vol_history }}"
        sequence:
          - choose:
              - conditions:
                  - condition: trigger
                    id:
                      - set
                sequence:
                  - alias: Set - Katas
                    event: set_variable_zen_history_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
                      value: "{{  value | default('') }}"
                      set_timestamp: "{{ set_timestamp | default(false) }}"
                      log_events: "{{ log_events }}"
              - conditions:
                  - condition: trigger
                    id:
                      - remove
                sequence:
                  - alias: Remove - Katas
                    event: remove_variable_zen_history_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
              - conditions:
                  - condition: trigger
                    id:
                      - clear
                sequence:
                  - alias: Clear - Katas
                    event: clear_variable_zen_history_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
      - conditions:
          - alias: Zen Dojo Cabinet
            condition: template
            value_template: "{{ volume_entity == vol_dojo }}"
        sequence:
          - choose:
              - conditions:
                  - condition: trigger
                    id:
                      - set
                sequence:
                  - alias: Set - Katas
                    event: set_variable_zen_dojo_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
                      value: "{{  value | default('') }}"
                      set_timestamp: "{{ set_timestamp | default(false) }}"
                      log_events: "{{ log_events }}"
              - conditions:
                  - condition: trigger
                    id:
                      - remove
                sequence:
                  - alias: Remove - Katas
                    event: remove_variable_zen_dojo_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
              - conditions:
                  - condition: trigger
                    id:
                      - clear
                sequence:
                  - alias: Clear - Katas
                    event: clear_variable_zen_dojo_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
      - conditions:
          - alias: Zen Friday History Cabinet
            condition: template
            value_template: "{{ volume_entity == vol_friday_history }}"
        sequence:
          - choose:
              - conditions:
                  - condition: trigger
                    id:
                      - set
                sequence:
                  - alias: Set - Katas
                    event: set_variable_zen_friday_history_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
                      value: "{{  value | default('') }}"
                      set_timestamp: "{{ set_timestamp | default(false) }}"
                      log_events: "{{ log_events }}"
              - conditions:
                  - condition: trigger
                    id:
                      - remove
                sequence:
                  - alias: Remove - Katas
                    event: remove_variable_zen_friday_history_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
              - conditions:
                  - condition: trigger
                    id:
                      - clear
                sequence:
                  - alias: Clear - Katas
                    event: clear_variable_zen_friday_history_cabinet
                    event_data:
                      key: "{{ key | default('') }}"
    default:
      - variables:
          final_response:
            status: error
            message: |
              Target volume {{ target }} not found.
      - stop: Target Volume Not Found
        response_variable: final_response
max: 10
